eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
keycloak:
  realm: aristo-realm
  auth-server-url: https://10.10.3.69:8443/
  resource: aristo-client
  public-client: false
  bearer-only: true
  credentials.secret: 4Gb89IYdSDTNBxmjiPO0PO6FOeOsc0ck
aristo:
  keycloak.base.url: https://10.10.3.69:8443/
