eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
keycloak:
  realm: aristo-realm
  auth-server-url: http://localhost:8080/
  resource: aristo-client
  public-client: true
  bearer-only: true
  credentials.secret: 5kvbSWrxdALAOtrkiLGCgv1TNLNeryx7
