eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
keycloak:
  realm: aristo-realm
  auth-server-url: http://aristo.gtech.com.tr:8080/
  resource: aristo-client
  public-client: false
  bearer-only: true
  credentials.secret: UoFIwh6cOOfpGIeNU13iOZi07JJwOrjr
aristo:
  keycloak.base.url: http://aristo.gtech.com.tr:8080/
  callbackUrl: https://aristo.gtech.com.tr:9191/api/checkouts/payment
  redirectUrl: https://aristo.gtech.com.tr:4200/user-profile/satin-aldiklarim/redirectFromPayment
