eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
keycloak:
  realm: aristo-realm
  auth-server-url: https://awls.corp.wizlinx.com:8443/
  resource: aristo-client
  public-client: false
  bearer-only: true
  credentials.secret: E8IgeK9SXankR9CCRSH1k2p8ExlkvXvQ
aristo:
  keycloak.base.url: https://awls.corp.wizlinx.com:8443/
  callbackUrl: http://awls.corp.wizlinx.com:9191/api/checkouts/payment
  redirectUrl: http://10.10.3.207:4200/user-profile/satin-aldiklarim/redirectFromPayment
