eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
keycloak:
  realm: aristo-realm
  auth-server-url: http://localhost:8080/
  resource: aristo-client
  public-client: false
  bearer-only: true
  credentials.secret: 5kvbSWrxdALAOtrkiLGCgv1TNLNeryx7
aristo:
  keycloak.base.url: http://localhost:8080/
  callbackUrl: http://awls.corp.wizlinx.com:9191/api/checkouts/payment
  redirectUrl: http://10.10.3.207:4200/user-profile/satin-aldiklarim/redirectFromPayment
